### ISSUE TITLE
请问这个配置文件应该怎么使用呢？

### ISSUE THREAD

**Issue by taomas** [yanhaijing/mysublime#1]
刚才看了颜大的[我的 Sublime Text 2 笔记](http://yanhaijing.com/tool/2014/10/24/my-sublime/)，觉得插件和快捷键总结的真到位了，现想请问一下这个sublime配置文件是怎么生成备份的呀？然后如果我要在新机器上安装以前的插件，该怎么使用呢？是应该在备份后覆盖sublime安装目录的一些文件吗？

**Comment by taomas** [comment]
还有一个问题想请问一下，我的sublime安装后，左侧sidebar显示中文文档信息就是乱码。请问颜大有什么好的解决方法吗？
![中文乱码](https://raw.githubusercontent.com/wendaosanshou/pic-repository/master/default.JPG)

**Comment by yanhaijing** [comment]
@wendaosanshou 需要这个插件 Package Syncing，装好后就可以了

ctrl + shift + p -> package syn 就能看到导入 导出的命令了

需要在旧电脑上导出配置，然后在新电脑上导入

**Comment by yanhaijing** [comment]
乱码的问题没遇到过，不知道原因

**Comment by taomas** [comment]
恩，会用了，谢谢。
